# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AditivosPan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cubierta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PreciosExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Relleno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rellenos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('multiplicador', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoPan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elID', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
