# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_delete_rellenos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopan',
            name='logo',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tamano',
            name='elID',
            field=models.IntegerField(),
        ),
    ]
