# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20171114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopan',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'tipPan'),
        ),
    ]
