# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_auto_20171115_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipopan',
            name='logo',
        ),
        migrations.AddField(
            model_name='tipopan',
            name='images',
            field=models.ImageField(blank=True, upload_to=b'tipoPan'),
        ),
    ]
