# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_auto_20171115_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopan',
            name='logo',
            field=models.CharField(max_length=1000),
        ),
    ]
