# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_auto_20171115_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivospan',
            name='logo',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cubierta',
            name='logo',
            field=models.CharField(default=3, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relleno',
            name='logo',
            field=models.CharField(default=4, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppings',
            name='logo',
            field=models.CharField(default=5, max_length=1000),
            preserve_default=False,
        ),
    ]
