# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_auto_20171115_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tamano',
            old_name='logo',
            new_name='tam',
        ),
    ]
