# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0015_remove_tamano_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relleno',
            name='logo',
        ),
    ]
