# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_remove_relleno_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relleno',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b'rellenos'),
        ),
    ]
