# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_relleno_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relleno',
            old_name='logo',
            new_name='logoRelleno',
        ),
    ]
