# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0019_auto_20171116_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relleno',
            name='logRel',
        ),
        migrations.AddField(
            model_name='relleno',
            name='logo',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
