# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0020_auto_20171116_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivospan',
            name='logo',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cubierta',
            name='logo',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tamano',
            name='logo',
            field=models.CharField(default=4, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppings',
            name='logo',
            field=models.CharField(default=6, max_length=1000),
            preserve_default=False,
        ),
    ]
